version: "3.8"
services:
  server:
    profiles: [dev]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    env_file:
      - app/.env
    depends_on:
      - mongo
  test:
    profiles: [test]
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - mongo
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    env_file:
      - mongo.config.env