version: "3.8"
services:
  server:
    build: .
    ports:
      - 8001:8001
    env_file:
      - app/.env
  mongo:
    image: mongo
    ports:
      - 27017:8002
    env_file:
      - mongo.config.env