name: AFTERHOURS GHCR CI

# Only perform on pushes to main branch
on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      # Pull code from repository to github actions runner
      - uses: actions/checkout@v3

      - name: Create .env file
        working-directory: ./server/app
        run: |
          touch .env
          echo "${{ secrets.SERVER_ENV }}" > .env

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build and push images to Registry
        working-directory: ./server
        run: |
          docker-compose --profile prod build
          docker-compose --profile prod publish